# Generated by Django 3.2.9 on 2021-12-10 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='is_actiive',
            new_name='is_active',
        ),
    ]
